test_that("tests to see if ff_analyze works", {
  test_dir = tempdir()
  groundtruth = file.path("../test_data/preprocessed/groundtruth/10N_110E/10N_110E_2023-01-01_groundtruth6m.tif")
  forestmask = file.path("../test_data/preprocessed/input/10N_110E/10N_110E_2021-01-01_initialforestcover.tif")
  predictions = file.path("../test_data/predictions/BRN/BRN_2023-01-01.tif")
  testthat::expect_no_error(polygons <- ff_analyze(predictions = predictions, groundtruth = groundtruth, forest_mask = forestmask,remove_empty = F))
  predictions = terra::rast(predictions)
  testthat::expect_no_error(polygons <- ff_analyze(predictions = predictions, groundtruth = groundtruth, forest_mask = forestmask,remove_empty = F,csv_filename = file.path(test_dir,"test.csv")))
  testthat::expect_true(file.exists(file.path(test_dir,"test.csv")))
  testthat::expect_gt(nrow(polygons),0)
  testthat::expect_gt(sum(polygons$FP+polygons$TP+polygons$FN),nrow(polygons))
  testthat::expect_error(polygons <- ff_analyze(predictions = predictions, groundtruth = groundtruth, forest_mask = "notexistingpath",remove_empty = F),regexp = "forest mask")
})
